/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/home/cpu.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={1}>
        <group scale={10}>
          <mesh
            
            castShadow = {props.cast}
            receiveShadow = {props.cast}
            geometry={nodes.Body4_1.geometry}
            material={materials["Material.007"]}
          />
          <mesh
            
            castShadow = {props.cast}
            receiveShadow = {props.cast}
            geometry={nodes.Body4_2.geometry}
            material={materials["Steel - Satin.001"]}
          />
        </group>
        <mesh
          
          castShadow = {props.cast}
          receiveShadow = {props.cast}
          geometry={nodes.Body40.geometry}
          material={materials["Material.009"]}
          scale={10}
        />
        <mesh
          
          castShadow = {props.cast}
          receiveShadow = {props.cast}
          geometry={nodes.Body41.geometry}
          material={materials["Material.010"]}
          scale={10}
        />
        <mesh
                    castShadow = {props.cast}
                    receiveShadow = {props.cast}
          
          geometry={nodes.Body42.geometry}
          material={materials["Material.004"]}
          scale={10}
        />
        <mesh
          
          castShadow = {props.cast}
          receiveShadow = {props.cast}
          geometry={nodes.Body43.geometry}
          material={materials["Material.004"]}
          scale={10}
        />
        <mesh
          
          castShadow = {props.cast}
          receiveShadow = {props.cast}
          geometry={nodes.Body44.geometry}
          material={materials["Material.004"]}
          scale={10}
        />
        <mesh
          
          castShadow = {props.cast}
          receiveShadow = {props.cast}
          geometry={nodes.Body45.geometry}
          material={materials["Material.004"]}
          scale={10}
        />
        <mesh
          
          castShadow = {props.cast}
          receiveShadow = {props.cast}
          geometry={nodes.Body46.geometry}
          material={materials["Material.004"]}
          scale={10}
        />
        <mesh
          
          castShadow = {props.cast}
          receiveShadow = {props.cast}
          geometry={nodes.Body49.geometry}
          material={materials["Material.007"]}
          scale={10}
        />
        <mesh
          
          castShadow = {props.cast}
          receiveShadow = {props.cast}
          geometry={nodes.Body50.geometry}
          material={materials["Material.013"]}
          scale={10}
        />
        <mesh
          
          castShadow = {props.cast}
          receiveShadow = {props.cast}
          geometry={nodes.Body51.geometry}
          material={materials["Material.014"]}
          scale={10}
        />
        <mesh
          
          castShadow = {props.cast}
          receiveShadow = {props.cast}
          geometry={nodes.Body52.geometry}
          material={materials["Material.012"]}
          scale={10}
        />
        <mesh
          
          castShadow = {props.cast}
          receiveShadow = {props.cast}
          geometry={nodes.Body53.geometry}
          material={materials["Material.015"]}
          scale={10}
        />
        <mesh
                    castShadow = {props.cast}
                    receiveShadow = {props.cast}
          
          geometry={nodes.Body54.geometry}
          material={materials["Material.007"]}
          scale={10}
        />
        <group scale={10}>
          <mesh
                      castShadow = {props.cast}
                      receiveShadow = {props.cast}
            
            geometry={nodes.Body55_1.geometry}
            material={materials["Material.007"]}
          />
          <mesh
            
            castShadow = {props.cast}
            receiveShadow = {props.cast}
            geometry={nodes.Body55_2.geometry}
            material={materials["Material.011"]}
          />
        </group>
        <mesh
                    castShadow = {props.cast}
                    receiveShadow = {props.cast}
          
          geometry={nodes.Body56.geometry}
          material={materials["Material.018"]}
          scale={10}
        />
        <mesh
                    castShadow = {props.cast}
                    receiveShadow = {props.cast}
          
          geometry={nodes.Body57.geometry}
          material={materials["Material.018"]}
          scale={10}
        />
        <mesh
                    castShadow = {props.cast}
                    receiveShadow = {props.cast}
          
          geometry={nodes.Body60.geometry}
          material={materials["Steel - Satin"]}
          scale={10}
        />
        <mesh
                    castShadow = {props.cast}
                    receiveShadow = {props.cast}
          
          geometry={nodes.Body61.geometry}
          material={materials["Steel - Satin"]}
          scale={10}
        />
        <mesh
                    castShadow = {props.cast}
                    receiveShadow = {props.cast}
          
          geometry={nodes.Body62.geometry}
          material={materials["Material.018"]}
          scale={10}
        />
        <mesh
                    castShadow = {props.cast}
                    receiveShadow = {props.cast}
          
          geometry={nodes.Body63.geometry}
          material={materials["Material.018"]}
          scale={10}
        />
        <mesh
                    castShadow = {props.cast}
                    receiveShadow = {props.cast}
          
          geometry={nodes.Body64.geometry}
          material={materials["Material.001"]}
          scale={10}
        />
        <mesh
                    castShadow = {props.cast}
                    receiveShadow = {props.cast}
          
          geometry={nodes.Body65.geometry}
          material={materials["Material.001"]}
          scale={10}
        />
        <group scale={10}>
          <mesh
                      castShadow = {props.cast}
                      receiveShadow = {props.cast}
            
            geometry={nodes.Body7_1.geometry}
            material={materials["Material.001"]}
          />
          <mesh
                      castShadow = {props.cast}
                      receiveShadow = {props.cast}
            
            geometry={nodes.Body7_2.geometry}
            material={materials["Steel - Satin.001"]}
          />
          <mesh
                      castShadow = {props.cast}
                      receiveShadow = {props.cast}
            
            geometry={nodes.Body7_3.geometry}
            material={materials["Material.006"]}
          />
        </group>
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={1}>
        <group
          position={[-17.3, -26.13, 22.03]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        >
          <mesh
                      castShadow = {props.cast}
                      receiveShadow = {props.cast}
            
            geometry={nodes.Body1_1.geometry}
            material={materials["Steel - Satin.002"]}
          />
          <mesh
                      castShadow = {props.cast}
                      receiveShadow = {props.cast}
            
            geometry={nodes.Body1_2.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group
          position={[-10.94, -26.13, 22.03]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        >
          <mesh
                      castShadow = {props.cast}
                      receiveShadow = {props.cast}
            
            geometry={nodes.Body1002_1.geometry}
            material={materials["Steel - Satin.002"]}
          />
          <mesh
                      castShadow = {props.cast}
                      receiveShadow = {props.cast}
            
            geometry={nodes.Body1002_2.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group
          position={[-3.95, -26.13, 22.03]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        >
          <mesh
            
            castShadow = {props.cast}
            receiveShadow = {props.cast}
            geometry={nodes.Body1003_1.geometry}
            material={materials["Steel - Satin.002"]}
          />
          <mesh
            
            castShadow = {props.cast}
            receiveShadow = {props.cast}
            geometry={nodes.Body1003_2.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group
          position={[3.02, -26.13, 22.03]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        >
          <mesh
                      castShadow = {props.cast}
                      receiveShadow = {props.cast}
            
            geometry={nodes.Body1004_1.geometry}
            material={materials["Steel - Satin.002"]}
          />
          <mesh
                      castShadow = {props.cast}
                      receiveShadow = {props.cast}
            
            geometry={nodes.Body1004_2.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group
          position={[9.35, -26.13, 22.03]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        >
          <mesh
                      castShadow = {props.cast}
                      receiveShadow = {props.cast}
            
            geometry={nodes.Body1005_1.geometry}
            material={materials["Steel - Satin.002"]}
          />
          <mesh
            
            castShadow = {props.cast}
            receiveShadow = {props.cast}
            geometry={nodes.Body1005_2.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group
          position={[-17.09, -26.13, 36.41]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        >
          <mesh
            
            castShadow = {props.cast}
            receiveShadow = {props.cast}
            geometry={nodes.Body1011_1.geometry}
            material={materials["Steel - Satin.002"]}
          />
          <mesh
            
            castShadow = {props.cast}
            receiveShadow = {props.cast}
            geometry={nodes.Body1011_2.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group
          position={[-10.73, -26.13, 36.41]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        >
          <mesh
                      castShadow = {props.cast}
                      receiveShadow = {props.cast}
            
            geometry={nodes.Body1012_1.geometry}
            material={materials["Steel - Satin.002"]}
          />
          <mesh
                      castShadow = {props.cast}
                      receiveShadow = {props.cast}
            
            geometry={nodes.Body1012_2.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group
          position={[-3.74, -26.13, 36.41]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        >
          <mesh
                      castShadow = {props.cast}
                      receiveShadow = {props.cast}
            
            geometry={nodes.Body1013_1.geometry}
            material={materials["Steel - Satin.002"]}
          />
          <mesh
                      castShadow = {props.cast}
                      receiveShadow = {props.cast}
            
            geometry={nodes.Body1013_2.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group
          position={[3.23, -26.13, 36.41]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        >
          <mesh
                      castShadow = {props.cast}
                      receiveShadow = {props.cast}
            
            geometry={nodes.Body1014_1.geometry}
            material={materials["Steel - Satin.002"]}
          />
          <mesh
                      castShadow = {props.cast}
                      receiveShadow = {props.cast}
            
            geometry={nodes.Body1014_2.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group
          position={[9.56, -26.13, 36.41]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        >
          <mesh
                      castShadow = {props.cast}
                      receiveShadow = {props.cast}
            
            geometry={nodes.Body1015_1.geometry}
            material={materials["Steel - Satin.002"]}
          />
          <mesh
                      castShadow = {props.cast}
                      receiveShadow = {props.cast}
            
            geometry={nodes.Body1015_2.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group
          position={[-17.09, -26.13, 52.43]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        >
          <mesh
                      castShadow = {props.cast}
                      receiveShadow = {props.cast}
            
            geometry={nodes.Body1016_1.geometry}
            material={materials["Steel - Satin.002"]}
          />
          <mesh
                      castShadow = {props.cast}
                      receiveShadow = {props.cast}
            
            geometry={nodes.Body1016_2.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group
          position={[-10.73, -26.13, 52.43]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        >
          <mesh
                      castShadow = {props.cast}
                      receiveShadow = {props.cast}
            
            geometry={nodes.Body1017_1.geometry}
            material={materials["Steel - Satin.002"]}
          />
          <mesh
            
            castShadow = {props.cast}
            receiveShadow = {props.cast}
            geometry={nodes.Body1017_2.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group
          position={[-3.74, -26.13, 52.43]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        >
          <mesh
                      castShadow = {props.cast}
                      receiveShadow = {props.cast}
            
            geometry={nodes.Body1018_1.geometry}
            material={materials["Steel - Satin.002"]}
          />
          <mesh
            
            castShadow = {props.cast}
            receiveShadow = {props.cast}
            geometry={nodes.Body1018_2.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group
          position={[3.23, -26.13, 52.43]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        >
          <mesh
                      castShadow = {props.cast}
                      receiveShadow = {props.cast}
            
            geometry={nodes.Body1019_1.geometry}
            material={materials["Steel - Satin.002"]}
          />
          <mesh
            
            castShadow = {props.cast}
            receiveShadow = {props.cast}
            geometry={nodes.Body1019_2.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group
          position={[9.56, -26.13, 52.43]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={10}
        >
          <mesh
                      castShadow = {props.cast}
                      receiveShadow = {props.cast}
            
            geometry={nodes.Body1020_1.geometry}
            material={materials["Steel - Satin.002"]}
          />
          <mesh
            
            castShadow = {props.cast}
            receiveShadow = {props.cast}
            geometry={nodes.Body1020_2.geometry}
            material={materials["Material.002"]}
          />
        </group>
      </group>
      <group position={[4, 38, -30]} scale={0.2}>
        <mesh
                    castShadow = {props.cast}
                    receiveShadow = {props.cast}
          
          geometry={nodes.Mesh.geometry}
          material={materials["Material #27"]}
        />
        <mesh
          
          castShadow = {props.cast}
          receiveShadow = {props.cast}
          geometry={nodes.Mesh_1.geometry}
          material={materials["Material #28"]}
        />
        <mesh
          
          castShadow = {props.cast}
          receiveShadow = {props.cast}
          geometry={nodes.Mesh_2.geometry}
          material={materials["Material #29"]}
        />
        <mesh
          
          castShadow = {props.cast}
          receiveShadow = {props.cast}
          geometry={nodes.Mesh_3.geometry}
          material={materials["Material #30"]}
        />
        <mesh
          
          castShadow = {props.cast}
          receiveShadow = {props.cast}
          geometry={nodes.Mesh_4.geometry}
          material={materials["Material #30"]}
        />
      </group>
      <mesh
        
        castShadow = {props.cast}
        receiveShadow = {props.cast}
        geometry={nodes.Plane.geometry}
        material={materials["Material.005"]}
        position={[34, 0, -23.8]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={11}
      />
    </group>
  );
}

useGLTF.preload("/home/cpu.glb");
