/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/home/halo.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[1.95, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ODST_Print_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ODST_Print_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/home/halo.glb");
