/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/home/Ironman.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group scale={0.27}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_11.geometry}
                material={materials.Head}
              />
            </group>
            <group scale={0.27}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_14.geometry}
                material={materials.Head}
              />
            </group>
            <group scale={0.27}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_17.geometry}
                material={materials.Head}
              />
            </group>
            <group scale={0.27}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_20.geometry}
                material={materials.Head}
              />
            </group>
            <group scale={0.27}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_23.geometry}
                material={materials.Head}
              />
            </group>
            <group scale={0.27}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_26.geometry}
                material={materials.Head}
              />
            </group>
            <group scale={0.27}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_29.geometry}
                material={materials.Eyes}
              />
            </group>
            <group scale={0.27}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_8.geometry}
                material={materials["Material.001"]}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/home/Ironman.glb");
