/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/home/mariobros.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="CANO"
          castShadow
          receiveShadow
          geometry={nodes.CANO.geometry}
          material={materials.MAT_CANO}
          position={[4.54, 0, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.1}
        />
        <mesh
          name="BOX_ITEM"
          castShadow
          receiveShadow
          geometry={nodes.BOX_ITEM.geometry}
          material={materials.MAT_BOXITEM}
          position={[0, 15.44, -0.19]}
          scale={0.7}
        >
          <mesh
            name="BOX_ITEM_INT01"
            castShadow
            receiveShadow
            geometry={nodes.BOX_ITEM_INT01.geometry}
            material={materials["03 - Default"]}
            position={[10, 7.05, 15.61]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={0.51}
          />
          <mesh
            name="BOX_ITEM_INT02"
            castShadow
            receiveShadow
            geometry={nodes.BOX_ITEM_INT02.geometry}
            material={materials["03 - Default"]}
            position={[15.61, 7.05, -10]}
            rotation={[Math.PI / 2, 0, Math.PI]}
            scale={0.51}
          />
          <mesh
            name="BOX_ITEM_INT03"
            castShadow
            receiveShadow
            geometry={nodes.BOX_ITEM_INT03.geometry}
            material={materials["03 - Default"]}
            position={[-10, 7.05, -15.61]}
            rotation={[Math.PI / 2, 0, Math.PI / 2]}
            scale={0.51}
          />
          <mesh
            name="BOX_ITEM_INT04"
            castShadow
            receiveShadow
            geometry={nodes.BOX_ITEM_INT04.geometry}
            material={materials["03 - Default"]}
            position={[-15.61, 7.05, 10]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.51}
          />
        </mesh>
        <mesh
          name="BOMB_CORPO"
          castShadow
          receiveShadow
          geometry={nodes.BOMB_CORPO.geometry}
          material={materials["MAT_BOMB_CORPO.001"]}
          position={[0.42, 11.78, 27.09]}
          rotation={[Math.PI, -1.22, Math.PI]}
          scale={0.5}
        >
          <mesh
            name="BOMB_CORDA_BASE"
            castShadow
            receiveShadow
            geometry={nodes.BOMB_CORDA_BASE.geometry}
            material={materials["MAT_BOMB_CORDA.001"]}
            position={[-0.02, 0, -36.48]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.82}
          >
            <mesh
              name="BOMB_CORDA_TOPO"
              castShadow
              receiveShadow
              geometry={nodes.BOMB_CORDA_TOPO.geometry}
              material={materials["MAT_BOMB_CORDA.001"]}
              position={[2, 1.68, 0]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={0.66}
            />
          </mesh>
          <mesh
            name="BOMB_OLHO_DIR"
            castShadow
            receiveShadow
            geometry={nodes.BOMB_OLHO_DIR.geometry}
            material={materials["MAT_BOMB_OLHO.001"]}
            position={[-6.25, 7.97, 22.65]}
            rotation={[-0.42, -0.25, -0.11]}
            scale={1.36}
          />
          <mesh
            name="BOMB_OLHO_ESQ"
            castShadow
            receiveShadow
            geometry={nodes.BOMB_OLHO_ESQ.geometry}
            material={materials["MAT_BOMB_OLHO.001"]}
            position={[7.36, 7.89, 22.23]}
            rotation={[-0.46, 0.28, 0.14]}
            scale={1.36}
          />
          <mesh
            name="BOMB_TOPO"
            castShadow
            receiveShadow
            geometry={nodes.BOMB_TOPO.geometry}
            material={materials["MAT_BOMB_TOPO.001"]}
            position={[0, 25.05, 0]}
          >
            <mesh
              name="BOMB_PAVIOQ"
              castShadow
              receiveShadow
              geometry={nodes.BOMB_PAVIOQ.geometry}
              material={materials["MAT_BOMB_PAVIO.001"]}
              position={[5.41, 13.4, 0]}
              rotation={[Math.PI / 2, 0, 0]}
            />
          </mesh>
        </mesh>
        <mesh
          name="BOMB_PE_ESQ"
          castShadow
          receiveShadow
          geometry={nodes.BOMB_PE_ESQ.geometry}
          material={materials["MAT_BOMB_PERNINHAS.001"]}
          position={[3.62, -10.34, 22.52]}
          rotation={[Math.PI, -0.93, Math.PI]}
          scale={0.5}
        />
        <mesh
          name="BOMB_PE_DIR"
          castShadow
          receiveShadow
          geometry={nodes.BOMB_PE_DIR.geometry}
          material={materials["MAT_BOMB_PERNINHAS.001"]}
          position={[0.42, -10.29, 19.8]}
          rotation={[Math.PI, -1.25, Math.PI]}
          scale={0.5}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/home/mariobros.glb");
