/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/home/pedestal.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body1.geometry}
          material={materials["Steel - Satin"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={40}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/home/pedestal.glb");
