/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/home/blackhole.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={1}>
        <group scale={10}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Body1_1.geometry}
            material={materials["Steel - Satin"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Body1_2.geometry}
            material={materials["Material.001"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/home/blackhole.glb");

