/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/home/tetris3.glb");
  return (
    <group {...props} dispose={null}> 
      <mesh

        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[0, 0, 0]}
        scale={[1, 2, 1]}
      />
    </group>
  );
}

useGLTF.preload("/home/tetris3.glb");
