/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/home/tetris5.glb");
  return (
    <group {...props} dispose={null}>
      <mesh

        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[0, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/home/tetris5.glb");
