export const List = [
    {
        id:1,
        name: "Caritapp iOS",
        date: "Sept 2022 - Oct 2023",
        description: "Developed (as a team) a mobile application for a local NGO to manage and enroll volunteers.",
        completeDescription: <><p>Developed (as a team) a mobile application for a local ONG to manage volunteers.</p><p style={{marginTop:"0.6rem"}}>Created a RESTful API with Flask and used Swift for iOS development.</p></>,
        tags: ["Frontend", "Backend", "Mobile", "Databases"],
        technologies: ["Swift", "Flask", "MySQL","Python"],
        img: "/thumbnails/caritapp.png",
        modalImg:"/modalImg/caritapp.png",
        video:"/videos/caritapp.mp4"
    },
    {
        id:2,
        name: "Multiagent Systems",
        date: "Nov 2022",
        description: "Modeled (as a team) a roundabout and a warehouse with agents that took decisions given some rules.",
        completeDescription: <><p>Modeled two multi-agent systems as a team. Agents made decisions and interacted with each other.</p><p style={{marginTop:"0.6rem"}}>Used Agent-based modeling in Python, and simulated on Unity.</p></>,
        tags: ["Backend", "Unity", "Simulation"],
        technologies: ["Python", "Mesa", "Flask", "Unity"],
        img: "/thumbnails/agents.png",
        modalImg:"/modalImg/agents.png",
        github: "https://github.com/JorgeLoredo-1852/Agentes",
        video: "/videos/agents.mp4"
    },
    {
        id:3,
        name: "Personal Portfolio",
        date: "Dec 2022 - Jan 2023",
        description: "A trip into my mind. Hope you enjoy it. Personal portfolio built with React, ThreeJS, tears and a lot of joy",
        completeDescription: <><p>Personal portfolio built with React, ThreeJS and a lot of joy.</p><p style={{marginTop:"0.6rem"}}>I hope you enjoyed visiting this website !!! :))) </p></>,
        tags: ["Frontend", "3D Modeling"],
        technologies: ["ReactJS", "ThreeJS", "CSS"],
        img: "/thumbnails/portfolio.png",
        modalImg:"/modalImg/portfolio.png",
        video:"/videos/Jgx.mp4"
    },
    { 
        id: 4,
        name: "Computing HL (IB)",
        date: "May 2020",
        description: "IB Computer Science High Level Internal Assessment focused on developing a desktop app for a local business",
        completeDescription: <><p>IB Computer Science High Level Internal Assessment focused on developing a desktop app for a local business</p><p style={{marginTop:"0.6rem"}}>OOP Application </p><p style={{marginTop:"0.6rem"}}>International Baccalaureate Grade: 6/7</p></>,
        tags: ["Backend", "Docs"],
        technologies: ["Java"],
        img: "/thumbnails/portilla.png",
        modalImg:"/modalImg/portilla.png",
        github:"https://github.com/JorgeLoredo-1852/High-School-Projects",
        video:"/videos/portilla.mp4"
    },
    {
        id: 5,
        name: "Photo Generation",
        date: "August 2020",
        description: "Created a neural network to edit photos as part of the Deep Learning specialization by Andrew Ng",
        completeDescription: <><p>Created a neural network to edit photos as part of the Deep Learning specialization by Andrew Ng.</p><p style={{marginTop:"0.6rem"}}>Tunned parameters and regularized data via Tensorflow</p></>,
        tags: ["Docs"],
        technologies: ["Tensorflow","Python"],
        img: "/thumbnails/ml.png",
        modalImg:"/modalImg/ml.png",
        video: "/videos/ML.mp4"
    },
    {
        id: 6,
        name: "Maze Robot",
        date: "Oct 2020",
        description: "Created a robot that could solve a maze given various requirements for Roborregos Candidates 2020",
        completeDescription: <><p>Created a robot that could solve a maze given various requirements for Roborregos Candidates 2020</p><p style={{marginTop:"0.6rem"}}>First place among +25 teams at the university</p></>,
        tags: ["3D Modeling","Competition"],
        technologies: ["Fusion 360"],
        img: "/thumbnails/cars.png",
        modalImg:"/modalImg/cars.png",
        link: "https://gallery.autodesk.com/projects/155725/maze-robot-solver",
        video: "/videos/robot.mp4"
    },
    { 
        id: 7,
        name: "Misc. Web",
        date: "Dec 2020 - Apr 2021",
        description: "Coded +10 websites/templates as part of 3 online courses with modern CSS, HTML, Javascript and React",
        completeDescription: <><p>Coded +10 websites/templates as part of 3 online courses.</p><p style={{marginTop:"0.6rem"}}>1. Advanced CSS and Sass: Flexbox, Grid, Animations and More! by J. Schmedtmann </p> <p>2. Modern React with Redux [2023 Update] by S. Grider </p><p>3. HTML, CSS, and Javascript for Web Developers by John Hopkins University</p></>,
        tags: ["Frontend"],
        technologies: ["ReactJS", "Sass", "Redux", "CSS", "HTML"],
        img: "/thumbnails/simi.png",
        modalImg:"/modalImg/simi.png",
        github: "https://github.com/JorgeLoredo-1852/Website-1stProject",
        link: "https://drsimi7.netlify.app/",
        video: "/videos/Simi.mp4"
    },
    { 
        id: 8,
        name: "SEMS: Monitoring",
        date: "Jan 2021 - June 2021",
        description: "Developed (team) a monitoring system which tracks factors of the student community in a post-pandemic scenario",
        completeDescription: <><p>Developed as a team a web application that generates data on factors that impact the health of the student community through a monitoring system for a post-pandemic scenario. </p><p style={{marginTop:"0.6rem"}}>Created a dashboard that allows the user to view and interact with the metrics of the student flow at the university, as well as record environmental variables in real-time.</p><p style={{marginTop:"0.6rem"}}>First place in “Conexión Tec” competition in the category "Software Prototype Development."</p></>,
        tags: ["Frontend", "IOT", "Competition", "Docs"],
        technologies: ["ReactJS", "Sass", "Redux"],
        img: "/thumbnails/covid.png",
        modalImg:"/modalImg/covid.png",
        link: "https://conecta.tec.mx/es/noticias/monterrey/educacion/el-software-que-analiza-estudios-urbanos-para-cumplir-medidas-vs-covid?_hsmi=147996003&_hsenc=p2ANqtz-_7cAvOiumdQwPtBrJ9_JE2yOIYHzsrNFaJoJz82yxzUDAfCpttr6st43RsGd6INLGgnak37S7q6SJ0yjYCphcUpuFFvA",
        video: "/videos/covid.mp4"        
    },
    {
        id:9,
        name: "Gas Leak Simulation",
        date: "May 2022",
        description: "Modeled (as a team) a gas leak via using a heat map in a factory given CO2 indices andemployee movement",
        completeDescription: <><p>Modeled (as a team) a gas leak via using a heat map in a factory given CO2 indices andemployee movement.</p><p style={{marginTop:"0.6rem"}}>Created a script to generate raw data, simulated in Unity and rendered to a web application via Web GL.</p></>,
        tags: ["Frontend","Backend","Databases", "Unity", "Simulation"],
        technologies: ["Unity", "ReactJS", "NodeJS"],
        img: "/thumbnails/construccion.png",
        modalImg:"/modalImg/construccion.png",
        video: "/videos/Ternium.mp4"
    },
    {
        id:10,
        name: "Moonlight NFT Labs",
        date: "Dec 2021 - Sept 2022",
        description: "Developed and offered a series of blockchain-decentralized applications on Ethereum, Avalanche, Terra, and Solana.",
        completeDescription: <><p>Developed and offered a series of blockchain-decentralized applications on Ethereum, Avalanche, Terra, and Solana.</p><p style={{marginTop:"0.6rem"}}>Including a Non-Fungible Token (NFT) collection, multichain launchpad, sales, and verification bot with customized smart contracts.</p></>,
        tags: ["Frontend", "Backend", "Web 3.0"],
        technologies: ["ReactJS", "NodeJS", "Redux", "Sass", "Solidity", "Rust", "Moralis", "EtherJS"],
        img: "/thumbnails/moonlight.png",
        modalImg:"/modalImg/moonlight.png",
        link: "https://moonlight-digital-art-and-assest.gitbook.io/werewolves-100-profit-share-+-multichain-service/",
        youtube: "https://www.youtube.com/@moonlightnfts6613",
        twitter: "https://twitter.com/MoonlightNFTLab",
        video: "/videos/moonlight.mp4"
    },
    {
        id:11,
        name: "HackMTY Challenge",
        date: "Sept 2022",
        description: "First place in Hack MTY - Banorte's Challenge (team), by designing a new way to retain young clients through gamification.",
        completeDescription: <><p>First place in Hack MTY - Banorte Challenge, the biggest student hackathon in Mexico, by designing a new way to attract young clients through gamification.</p><p style={{marginTop:"0.6rem"}}>Created the complete design of the application/gadgets and market study in 24 hours.</p></>,
        tags: ["Docs", "Competition"],
        technologies: ["Python", "Figma"],
        img: "/thumbnails/banorte.png",
        modalImg:"/modalImg/banorte.png",
        video: "/videos/hackmty.mp4"
    },
]