export const List = [
    {
        id:1,
        name: "Personal Portfolio",
        date: "Dec 2022 - Jan 2023",
        description: "A trip into my mind. Hope you enjoy it. Personal portfolio built with React, ThreeJS, tears and a lot of joy",
        completeDescription: <><p>Personal portfolio built with React, ThreeJS and a lot of joy.</p><p style={{marginTop:"0.6rem"}}>I hope you enjoyed visiting this website !!! :))) </p></>,
        tags: ["Frontend", "3D Modeling"],
        technologies: ["ReactJS", "ThreeJS", "CSS"],
        img: "/thumbnails/portfolio.png",
        modalImg:"/modalImg/portfolio.png",
    },
    {
        id:2,
        name: "Multiagent Systems",
        date: "Nov 2022",
        description: "Modeled (as a team) a roundabout and a warehouse with agents that took decisions given some rules.",
        completeDescription: <><p>Modeled two multi-agent systems as a team. Agents made decisions and interacted with each other.</p><p style={{marginTop:"0.6rem"}}>Used Agent-based modeling in Python, and simulated on Unity.</p></>,
        tags: ["Backend", "Simulation"],
        technologies: ["Python", "Mesa", "Flask", "Unity"],
        img: "/thumbnails/agents.png",
        modalImg:"/modalImg/agents.png",
        github: "https://github.com/JorgeLoredo-1852/Agentes",
    },
    {
        id:3,
        name: "Caritapp iOS",
        date: "Sept 2022 - Oct 2023",
        description: "Developed (as a team) a mobile application for a local NGO to manage and enroll volunteers.",
        completeDescription: <><p>Developed (as a team) a mobile application for a local ONG to manage volunteers.</p><p style={{marginTop:"0.6rem"}}>Created a RESTful API with Flask and used Swift for iOS development.</p></>,
        tags: ["Frontend", "Backend", "Mobile", "Databases"],
        technologies: ["Swift", "Flask", "MySQL","Python"],
        img: "/thumbnails/caritapp.png",
        modalImg:"/modalImg/caritapp.png",
    },
    {
        id:4,
        name: "HackMTY Challenge",
        date: "Sept 2022",
        description: "First place in Hack MTY - Banorte's Challenge (team), by designing a new way to retain young clients through gamification.",
        completeDescription: <><p>First place in Hack MTY - Banorte Challenge, the biggest student hackathon in Mexico, by designing a new way to attract young clients through gamification.</p><p style={{marginTop:"0.6rem"}}>Created the complete design of the application/gadgets and market study in 24 hours.</p></>,
        tags: ["Docs", "Competition"],
        technologies: ["Python", "Figma"],
        img: "/thumbnails/banorte.png",
        modalImg:"/modalImg/banorte.png",
    },
    {
        id:5,
        name: "Moonlight NFT Labs",
        date: "Dec 2021 - Sept 2022",
        description: "Developed and offered a series of blockchain-decentralized applications on Ethereum, Avalanche, Terra, and Solana.",
        completeDescription: <><p>Developed and offered a series of blockchain-decentralized applications on Ethereum, Avalanche, Terra, and Solana.</p><p style={{marginTop:"0.6rem"}}>Including a Non-Fungible Token (NFT) collection, multichain launchpad, sales, and verification bot with customized smart contracts.</p></>,
        tags: ["Frontend", "Backend", "Web 3.0"],
        technologies: ["ReactJS", "NodeJS", "Redux", "Sass", "Solidity", "Rust", "Moralis", "EtherJS"],
        img: "/thumbnails/moonlight.png",
        modalImg:"/modalImg/moonlight.png",
        link: "https://moonlight-digital-art-and-assest.gitbook.io/werewolves-100-profit-share-+-multichain-service/",
        youtube: "https://www.youtube.com/@moonlightnfts6613",
        twitter: "https://twitter.com/MoonlightNFTLab",
    },
    {
        id:6,
        name: "Moonlight Launchpad",
        date: "Dec 2021 - Sept 2022",
        description: "Created a Multichain Launchpad with custom smart contracts implemented in a responsive web app to mint NFT tokens.",
        completeDescription: <><p>Built a Multichain Launchpad with custom smart contracts implemented in a responsive web app to mint NFT tokens.</p><p style={{marginTop:"0.6rem"}}>Created optimized smart contracts and APIs for EVMs (ETH, Avax), Solana, Terra.</p></>,
        tags: ["Frontend", "Backend", "Web 3.0"],
        technologies: ["ReactJS", "NodeJS", "Sass", "Solidity", "Rust", "EtherJS"],
        img: "/thumbnails/launchpad.png",
        modalImg:"/modalImg/launchpad.png",
        link: "https://moonlight-digital-art-and-assest.gitbook.io/werewolves-100-profit-share-+-multichain-service/",
        youtube: "https://www.youtube.com/watch?v=y42cmEiBsqw",
        twitter: "https://twitter.com/MoonlightNFTLab",
    },
    {
        id:7,
        name: "Moonlight Bots",
        date: "Dec 2021 - Sept 2022",
        description: "Deployed an NFT Sales bot as well as a Verification Bot to power DAOs (Decentralized autonomous organizations).",
        completeDescription: <><p>Deployed an NFT Sales bot as well as a Verification Bot to power DAOs (Decentralized autonomous organizations).</p><p style={{marginTop:"0.6rem"}}>Compatible with Twitter/Discord and block explorers in Ethereum, Avax, Solana and Terra</p></>,
        tags: ["Frontend", "Backend", "Web 3.0"],
        technologies: ["ReactJS", "NodeJS", "Redux", "Sass", "Moralis", "EtherJS"],
        img: "/thumbnails/bot.png",
        modalImg:"/modalImg/bot.png",
        link: "https://moonlight-digital-art-and-assest.gitbook.io/werewolves-100-profit-share-+-multichain-service/",
        youtube: "https://www.youtube.com/watch?v=Wg70E0fOBYM",
        twitter: "https://twitter.com/MoonlightNFTLab",
    },
    {
        id:8,
        name: "Web 3.0 Templates",
        date: "Aug 2022",
        description: "Created templates for blockchain-based applications on Solana (Staking Platform, Mystery Box Game)",
        completeDescription: <><p>Created templates for blockchain-based applications on Solana (Staking Platform, Mystery Box Game).</p><p style={{marginTop:"0.6rem"}}>Created a script to generate raw data, simulated in Unity and rendered to a web application via Web GL.</p></>,
        tags: ["Frontend","Web 3.0"],
        technologies: ["ReactJS", "CSS", "Material UI"],
        img: "/thumbnails/template.png",
        modalImg:"/modalImg/template.png",
        link: "https://main.d2juybscny22sl.amplifyapp.com/",
        link2: "https://main.d3nwwa1llv0ubk.amplifyapp.com/"
    },
    {
        id:9,
        name: "Gas Leak Simulation",
        date: "May 2022",
        description: "Modeled (as a team) a gas leak via using a heat map in a factory given CO2 indices andemployee movement",
        completeDescription: <><p>Modeled (as a team) a gas leak via using a heat map in a factory given CO2 indices andemployee movement.</p><p style={{marginTop:"0.6rem"}}>Created a script to generate raw data, simulated in Unity and rendered to a web application via Web GL.</p></>,
        tags: ["Frontend","Backend","Databases","Simulation"],
        technologies: ["Unity", "ReactJS", "NodeJS"],
        img: "/thumbnails/construccion.png",
        modalImg:"/modalImg/construccion.png",
    },
    {
        id: 10,
        name: "Energy efficiency",
        date: "Dec 2021",
        description: "Built (team) an IoT simulation to streamline the energy usage in a house given environmental variables",
        completeDescription: <><p>Built (team) an IoT simulation to streamline the energy usage in a house given environmental variables.</p><p style={{marginTop:"0.6rem"}}>Simulated locally on 2 machines and 2 physical microcontrollers.</p></>,
        tags: ["Backend","Databases", "IOT", "Simulation"],
        technologies: ["Arduino", "C++", "MySQL","Tableau","Python"],
        img: "/thumbnails/iot.png",
        modalImg:"/modalImg/iot.png",
    },
    { 
        id: 11,
        name: "SEMS: Monitoring",
        date: "Jan 2021 - June 2021",
        description: "Developed (team) a monitoring system which tracks factors of the student community in a post-pandemic scenario",
        completeDescription: <><p>Developed as a team a web application that generates data on factors that impact the health of the student community through a monitoring system for a post-pandemic scenario. </p><p style={{marginTop:"0.6rem"}}>Created a dashboard that allows the user to view and interact with the metrics of the student flow at the university, as well as record environmental variables in real-time.</p><p style={{marginTop:"0.6rem"}}>First place in “Conexión Tec” competition in the category "Software Prototype Development."</p></>,
        tags: ["Frontend", "IOT", "Competition", "Docs"],
        technologies: ["ReactJS", "Sass", "Redux"],
        img: "/thumbnails/covid.png",
        modalImg:"/modalImg/covid.png",
        link: "https://conecta.tec.mx/es/noticias/monterrey/educacion/el-software-que-analiza-estudios-urbanos-para-cumplir-medidas-vs-covid?_hsmi=147996003&_hsenc=p2ANqtz-_7cAvOiumdQwPtBrJ9_JE2yOIYHzsrNFaJoJz82yxzUDAfCpttr6st43RsGd6INLGgnak37S7q6SJ0yjYCphcUpuFFvA"
    },
    { 
        id: 12,
        name: "URL Shortener",
        date: "Dec 2020 - May 2021",
        description: "Developed in a team the Back-End for a link shortener that manages the information from the Roborregos robotics team.",
        completeDescription: <><p>Developed in a team of two the Back-End for a link shortener that manages the information from the Roborregos robotics team.</p></>,
        tags: ["Backend", "Databases"],
        technologies: ["PHP", "Laravel", "MySQL"],
        img: "/thumbnails/robolinks.png",
        modalImg:"/modalImg/robolinks.png",
    },
    { 
        id: 13,
        name: "Misc. Web",
        date: "Dec 2020 - Apr 2021",
        description: "Coded +10 websites/templates as part of 3 online courses with modern CSS, HTML, Javascript and React",
        completeDescription: <><p>Coded +10 websites/templates as part of 3 online courses.</p><p style={{marginTop:"0.6rem"}}>1. Advanced CSS and Sass: Flexbox, Grid, Animations and More! by J. Schmedtmann </p> <p>2. Modern React with Redux [2023 Update] by S. Grider </p><p>3. HTML, CSS, and Javascript for Web Developers by John Hopkins University</p></>,
        tags: ["Frontend"],
        technologies: ["ReactJS", "Sass", "Redux", "CSS", "HTML"],
        img: "/thumbnails/simi.png",
        modalImg:"/modalImg/simi.png",
        github: "https://github.com/JorgeLoredo-1852/Website-1stProject",
        link: "https://drsimi7.netlify.app/"
    },
    {
        id: 14,
        name: "Natours API",
        date: "March 2021",
        description: "Created a complete RESTful API with error handling, authentication, security, data modeling and more",
        completeDescription: <><p>Created a complete REST API with error handling, security, data modeling and more, as part of "NodeJS, Express, MongoDB & More: The Comlpete Bootcamp 2021"</p></>,
        tags: ["Backend","Databases"],
        technologies: ["MongoDB", "NodeJS", "Express"],
        img: "/thumbnails/natours.png",
        modalImg:"/modalImg/natours.png",
    },
    {
        id: 15,
        name: "Egg Collector",
        date: "Oct 2020",
        description: "Developed a magnetic stripe mechanism box for egg collection as part of a mechanics hackathon",
        completeDescription: <><p>Developed a magnetic stripe mechanism box for egg collection as part of a mechanics hackathon</p><p style={{marginTop:"0.6rem"}}>First place among +15 participants at the university</p></>,
        tags: ["3D Modeling","Competition"],
        technologies: ["Fusion 360"],
        img: "/thumbnails/egg.png",
        modalImg:"/modalImg/egg.png",
        link: "https://gallery.autodesk.com/projects/155724/egg-storing-box"
    },
    {
        id: 16,
        name: "Maze Robot",
        date: "Oct 2020",
        description: "Created a robot that could solve a maze given various requirements for Roborregos Candidates 2020",
        completeDescription: <><p>Created a robot that could solve a maze given various requirements for Roborregos Candidates 2020</p><p style={{marginTop:"0.6rem"}}>First place among +25 teams at the university</p></>,
        tags: ["3D Modeling","Competition"],
        technologies: ["Fusion 360"],
        img: "/thumbnails/cars.png",
        modalImg:"/modalImg/cars.png",
        link: "https://gallery.autodesk.com/projects/155725/maze-robot-solver"
    },
    {
        id: 17,
        name: "Game Jam",
        date: "Oct 2020",
        description: "Developed as a team a 2D RPG game set on the spooky horrors of Halloween during a 24h Hackathon.",
        completeDescription: <><p>Developed as a team a 2D RPG game set on the spooky horrors of Halloween during a 24h Hackathon.</p><p style={{marginTop:"0.6rem"}}>Fifth place among 15+ teams competing in the university.</p></>,
        tags: ["Competition"],
        technologies: ["Unity"],
        img: "/thumbnails/unity.png",
        modalImg:"/modalImg/unity.png",
    },
    {
        id: 18,
        name: "Photo Generation",
        date: "August 2020",
        description: "Created a neural network to edit photos as part of the Deep Learning specialization by Andrew Ng",
        completeDescription: <><p>Created a neural network to edit photos as part of the Deep Learning specialization by Andrew Ng.</p><p style={{marginTop:"0.6rem"}}>Tunned parameters and regularized data via Tensorflow</p></>,
        tags: ["Docs"],
        technologies: ["Tensorflow","Python"],
        img: "/thumbnails/ml.png",
        modalImg:"/modalImg/ml.png",
    },
    { 
        id: 19,
        name: "Mathematics HL (IB)",
        date: "May 2020",
        description: "IB Mathematics High Level Internal Assessment focused on finding the shortest path in a transportation network",
        completeDescription: <><p>IB Mathematics High Level Internal Assessment focused on finding the shortest path in a transportation network.</p><p style={{marginTop:"0.6rem"}}>Iterative algorithm that calculates all the possible paths in the transportation network on a specific Monterrey region using Dijkstra</p><p style={{marginTop:"0.6rem"}}>International Baccalaureate Grade: 6/7</p></>,
        tags: ["Docs"],
        technologies: ["Java"],
        img: "/thumbnails/math.png",
        modalImg:"/modalImg/math.png",
        github:"https://github.com/JorgeLoredo-1852/High-School-Projects"
    },
    { 
        id: 20,
        name: "Computing HL (IB)",
        date: "May 2020",
        description: "IB Computer Science High Level Internal Assessment focused on developing a desktop app for a local business",
        completeDescription: <><p>IB Computer Science High Level Internal Assessment focused on developing a desktop app for a local business</p><p style={{marginTop:"0.6rem"}}>OOP Application </p><p style={{marginTop:"0.6rem"}}>International Baccalaureate Grade: 6/7</p></>,
        tags: ["Backend", "Docs"],
        technologies: ["Java"],
        img: "/thumbnails/portilla.png",
        modalImg:"/modalImg/portilla.png",
        github:"https://github.com/JorgeLoredo-1852/High-School-Projects"
    },
    { 
        id: 21,
        name: "Proximité Installation",
        date: "Nov 2019",
        description: "Built an electronic art installation that got exposed in Marco Museum inspired in the exposition Présence Instable.",
        completeDescription: <><p>Built an electronic art installation that got exposed in Marco Museum inspired in the exposition Présence Instable.</p><p style={{marginTop:"0.6rem"}}>First approach to engineering, programming and electronics</p></>,
        tags: ["IOT"],
        technologies: ["C++","Arduino"],
        img: "/thumbnails/french.png",
        modalImg:"/modalImg/french.png",
    },
]