export { Home } from './Home/index'
export { Education } from './Education/index'
export { Navbar, NewNav } from './Navbar/index'
export { FeaturedProjects} from './FeaturedProjects/index'
export { ListProjects } from './ListProjects/index'
export { JGx } from './JGx/index'
export { Form3D } from './Form3D/index'
export { WorkScene } from './WorkScene/index'
export { Roles } from './Roles/index'
export { Courses } from './Courses/index'
export { LoadingModels } from './LoadingModels/index'
export { ModalProject } from './ModalProject/index'