export { Home } from './Home/index'
export { Education } from './Education/index'
export { Navbar, NewNav } from './Navbar/index'
export { FeaturedProjects} from './FeaturedProjects/index'
export { ListProjects } from './ListProjects/index'
export { JGx } from './JGx/index'