/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/PilarOracle.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MedGlobal_Group001.geometry}
        material={materials["Material.005"]}
        position={[1.07, 14.73, -5.75]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MedGlobal_Group002.geometry}
        material={nodes.MedGlobal_Group002.material}
        position={[1.07, 16.73, -0.14]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MedGlobal_Group004.geometry}
        material={nodes.MedGlobal_Group004.material}
        position={[1.07, 10.97, -0.15]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MedGlobal_Group005.geometry}
        material={nodes.MedGlobal_Group005.material}
        position={[1.07, 39.55, -5.6]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      />
      <group scale={[1, 40, 8]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          material={materials.Material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials["Material.002"]}
        position={[1, 28.21, 0]}
        scale={[0.2, 7, 7]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve.geometry}
        material={materials["SVGMat.001"]}
        position={[0.57, 28.22, 5.63]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve002.geometry}
        material={materials["SVGMat.004"]}
        position={[0.6, 37.54, -5.5]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={16}
      />
    </group>
  );
}

useGLTF.preload("/PilarOracle.glb");