/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/arrow.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arrow_v1.geometry}
        material={materials["Steel_-_Satin"]}
        position={[-0.65, 0, 0]}
        scale={0.18}
      />
    </group>
  );
}

useGLTF.preload("/arrow.glb");
