/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/boycolor.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body3001.geometry}
          material={materials["Material.008"]}
          scale={10}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body4001.geometry}
          material={materials["Material.008"]}
          scale={10}
        />
        <group scale={10}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Body2001_1.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Body2001_2.geometry}
            material={materials["Material.006"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Body2001_3.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Body2001_4.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Body2001_5.geometry}
            material={materials.Black_plastic}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials["Cheap Toy Plastic.005"]}
        position={[0.0251, -0.0248, 0.0032]} 
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.007}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text001.geometry}
        material={materials["Cheap Toy Plastic.005"]}
        rotation={[Math.PI / 2, 0, 0]}
        position={[0.0118, -0.0298, 0.0032]}
        scale={0.007}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text002.geometry}
        material={materials["Cheap Toy Plastic.003"]}
        position={[-0.003, -0.0125, 0.001]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.004}
      />
    </group>
  );
}

useGLTF.preload("/boycolor.glb");