/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/downArrow.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body1.geometry}
          material={materials["Steel - Satin"]}
          scale={10}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/downArrow.glb");
