/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export const Model = ({rotation, scale,  refa}) => {
    const { nodes, materials } = useGLTF("/nave.glb");
  return (
    <group rotation={rotation} dispose={null} ref={refa}>
      <group position={[0, 0.01, 0.1]} scale={scale}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["nave-inimiga-2_1"].geometry}
          material={materials["name-inimiga-2"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["nave-inimiga-2_2"].geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["nave-inimiga-2_3"].geometry}
          material={materials["Material.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/nave.glb");
