/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/rock3.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, 0.97, 0.04]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[1.8, 0.6, 1.2]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube057.geometry}
          material={materials.Main}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube057_1.geometry}
          material={materials.Edges}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/rock3.glb");
